version: '3.1'

services:
  database:
    
    image: mysql
    container_name: inventariobun24

    environment: 
      MYSQL_DATABASE: "inventario"
      MYSQL_USER: "orlando"
      MYSQL_PASSWORD: "nestor"
      MYSQL_ROOT_PASSWORD: "nestor"
    
    ports:
      - "3307:3306"

    volumes:
      - './mysql:/var/lib/mysql'
